- hosts: all
  become: yes
  vars:
    package: apache2
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: "{{ package }}"
      update_cache: yes

  - name: Start apache 
    ansible.builtin.service:
      name: "{{ package }}"
      state: started
      enabled: yes